name: build

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - id: build
        uses: addnab/docker-run-action@v3
        with:
          image: golang
          options: -v ${{ github.workspace }}:/work -w /work
          run: |
            make
